apiVersion: v1
kind: Service
metadata:
  name: enhanced-microservice-service
spec:
  selector:
    app: enhanced-microservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
